# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  desc "Hockey"
  lane :beta do
  build_app(scheme: "LoveDating",
            workspace: "LoveDating.xcworkspace",
            include_bitcode: true)
  hockey(
	api_token: "d0aadd9169eb404394d74f18447fc161",
  	ipa: "#{lane_context[SharedValues::IPA_OUTPUT_PATH]}",
  	notes: "Last commit: #{commit[:message]} by #{commit[:author]}"
   ) 
  end
end
